kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: apimanager
  namespace: wooribank
spec:
  wildcardDomain: apps.dokd4.mcnc.co.kr
  system:
    appSpec:
      masterContainerResources:
        requests:
          memory: "600Mi"
          cpu: "50m"
        limits:
          memory: "800Mi"
          cpu: "1000m"
      providerContainerResources:
        requests:
          memory: "600Mi"
          cpu: "50m"
        limits:
          memory: "800Mi"
          cpu: "1000m"
      developerContainerResources:
        requests:
          memory: "600Mi"
          cpu: "50m"
        limits:
          memory: "800Mi"
          cpu: "1000m"
    sidekiqSpec:
      resources:
        requests:
          memory: "500Mi"
          cpu: "100m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
    sphinxSpec:
      resources:
        requests:
          memory: "250Mi"
          cpu: "80m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
    redisResources:
      requests:
        memory: "256Mi"
        cpu: "150m"
      limits:
        memory: "32Gi"
        cpu: "500m"
    database:
      postgresql:
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
    memcachedResources:
      requests:
        memory: "600Mi"
        cpu: "50m"
      limits:
        memory: "800Mi"
        cpu: "1000m"
  backend:
    listenerSpec:
      resources:
        requests:
          memory: "550Mi"
          cpu: "500m"
        limits:
          memory: "700Mi"
          cpu: "1000m"
    workerSpec:
      resources:
        requests:
          memory: "50Mi"
          cpu: "150m"
        limits:
          memory: "300Mi"
          cpu: "1000m"
    cronSpec:
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "500Mi"
          cpu: "500m"
    redisResources:
      requests:
        memory: "1024Mi"
        cpu: "1000m"
      limits:
        memory: "32Gi"
        cpu: "2000m"
  apicast:
    productionSpec:
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "1000m"
    stagingSpec:
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "1000m"
  zync:
    appSpec:
      resources:
        requests:
          memory: "250Mi"
          cpu: "150m"
        limits:
          memory: "512Mi"
          cpu: "1"
    queSpec:
      resources:
        requests:
          memory: "250Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "1"
    databaseResources:
      requests:
        memory: "250Mi"
        cpu: "50m"
      limits:
        memory: "2Gi"
        cpu: "250m"
